#for dashboard app urls



from django.urls import path
from . import views
from . import admin_views

app_name = 'dashboard'

urlpatterns = [
    path('teacher-dashboard/', views.teacher_dashboard_view, name='teacher_dashboard'),
    path('high-school-teacher-dashboard/', views.teacher_dashboard_view, name='high_school_teacher_dashboard'),
    path('senior-high-teacher-dashboard/', views.teacher_dashboard_view, name='senior_high_teacher_dashboard'),
    path('university-college-teacher-dashboard/', views.teacher_dashboard_view, name='university_college_teacher_dashboard'),
    path('student-dashboard/', views.student_dashboard_view, name='student_dashboard'),
    path('high-school-dashboard/', views.student_dashboard_view, name='high_school_dashboard'),
    path('senior-high-dashboard/', views.student_dashboard_view, name='senior_high_dashboard'),
    path('university-college-dashboard/', views.student_dashboard_view, name='university_college_dashboard'),
    path('schedule/', views.schedule_view, name='schedule'),
    path('courses/', views.courses_view, name='courses'),
    path('courses/<int:course_id>/attendance-times/', views.instructor_update_attendance_times_view, name='instructor_update_attendance_times'),
    # Instructor course management
    path('instructor/courses/', views.instructor_courses_view, name='instructor_courses'),
    path('instructor/courses/add/', views.instructor_add_course_view, name='instructor_add_course'),
    path('instructor/courses/<int:course_id>/update/', views.instructor_update_course_view, name='instructor_update_course'),
    path('instructor/courses/<int:course_id>/delete/', views.instructor_delete_course_view, name='instructor_delete_course'),
    path('instructor/courses/<int:course_id>/archive/', views.instructor_archive_course_view, name='instructor_archive_course'),
    path('instructor/courses/archive-semester/', views.instructor_archive_semester_view, name='instructor_archive_semester'),
    path('instructor/courses/archive-school-year/', views.instructor_archive_school_year_view, name='instructor_archive_school_year'),
    path('instructor/courses/delete-semester/', views.instructor_delete_semester_view, name='instructor_delete_semester'),
    path('instructor/courses/<int:course_id>/', views.instructor_course_detail_view, name='instructor_course_detail'),
    path('instructor/courses/<int:course_id>/enrollments/', views.instructor_course_enrollments_view, name='instructor_course_enrollments'),
    path('instructor/courses/<int:course_id>/qr-code/', views.instructor_qr_code_view, name='instructor_qr_code'),
    path('student/qr-scanner/', views.student_qr_scanner_view, name='student_qr_scanner'),
    path('student/scan-qr-attendance/', views.student_scan_qr_attendance_view, name='student_scan_qr_attendance'),
    path('student/todays-status/', views.student_todays_status_view, name='student_todays_status'),
    path('student/attendance-log/', views.student_attendance_log_view, name='student_attendance_log'),
    path('instructor/programs-by-department/', views.instructor_get_programs_by_department_view, name='instructor_get_programs_by_department'),
    path('instructor/notifications/', views.instructor_notifications_view, name='instructor_notifications'),
    path('student/notifications/', views.student_notifications_view, name='student_notifications'),
    path('notifications/<int:notification_id>/read/', views.mark_notification_read_view, name='mark_notification_read'),
    path('notifications/<int:notification_id>/delete/', views.delete_notification_view, name='delete_notification'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read_view, name='mark_all_notifications_read'),
    path('notifications/delete-all/', views.delete_all_notifications_view, name='delete_all_notifications'),
    path('teacher/profile/update/', views.teacher_update_profile_view, name='teacher_update_profile'),
    path('student/profile/update/', views.student_update_profile_view, name='student_update_profile'),
    path('api/get-user-profile/', views.get_user_profile, name='get_user_profile'),
    path('api/get-custom-password/', views.get_custom_password_view, name='get_custom_password'),
    path('students/', views.students_view, name='students'),
    path('weekly-timetable/', views.weekly_timetable_view, name='weekly_timetable'),
    # Instructor: My Classes (monitoring)
    path('instructor/my-classes/', views.instructor_my_classes_view, name='instructor_my_classes'),
    path('instructor/courses/<int:course_id>/update-attendance-status/', views.instructor_update_attendance_status_view, name='instructor_update_attendance_status'),
    path('instructor/courses/<int:course_id>/update-enrollment-status/', views.instructor_update_enrollment_status_view, name='instructor_update_enrollment_status'),
    path('instructor/scan-student-school-id/', views.instructor_scan_student_school_id_view, name='instructor_scan_student_school_id'),
    path('instructor/scan-student-qr-code/', views.instructor_scan_student_qr_code_view, name='instructor_scan_student_qr_code'),
    path('instructor/scanned-students/', views.instructor_get_scanned_students_view, name='instructor_get_scanned_students'),
    path('instructor/biometric-students/', views.instructor_get_biometric_students_view, name='instructor_get_biometric_students'),
    path('instructor/decode-image/', views.instructor_decode_image_view, name='instructor_decode_image'),
    path('instructor/course-enrollments/<int:course_id>/', views.instructor_course_enrollments_view, name='instructor_course_enrollments'),
    path('instructor/register-student-qr-code/', views.instructor_register_student_qr_code_view, name='instructor_register_student_qr_code'),
    # Student self-register QR (students can register their own QR codes to their enrolled course)
    path('student/register-qr-code/', views.student_register_qr_code_view, name='student_register_qr_code'),
    path('student/register-qr-code-with-instructor/', views.student_register_qr_code_with_instructor_view, name='student_register_qr_code_with_instructor'),
    path('student/get-registration-instructors/', views.student_get_registration_instructors_view, name='student_get_registration_instructors'),
    # Biometric registration and verification endpoints
    path('instructor/register-student-biometric/', views.instructor_register_student_biometric_view, name='instructor_register_student_biometric'),
    path('student/register-biometric/', views.student_register_biometric_view, name='student_register_biometric'),
    path('student/verify-biometric/', views.student_verify_biometric_view, name='student_verify_biometric'),
    path('instructor/check-biometric-registration/', views.instructor_check_biometric_registration_view, name='instructor_check_biometric_registration'),
    path('api/biometric/enroll/', views.api_biometric_enroll_view, name='api_biometric_enroll'),
    path('api/biometric/confirm/', views.api_biometric_confirm_fingerprint_view, name='api_biometric_confirm'),
    path('api/biometric/verify/', views.api_biometric_verify_view, name='api_biometric_verify'),
    path('api/biometric/scan-attendance/', views.api_biometric_scan_attendance_view, name='api_biometric_scan_attendance'),
    path('api/biometric/check-enrollment-lock/', views.check_instructor_enrollment_lock, name='check_instructor_enrollment_lock'),
    path('api/check-biometric/', views.api_check_biometric_view, name='api_check_biometric'),
    path('api/instructor/courses/', views.api_get_instructor_courses_view, name='api_get_instructor_courses'),
    path('api/student/enrolled-courses/', views.api_get_student_enrolled_courses_view, name='api_get_student_enrolled_courses'),
    # Instructor enable/disable registration for courses
    path('instructor/check-registration-status/', views.check_course_registration_status, name='check_course_registration_status'),
    path('instructor/enable-course-registration/', views.enable_course_registration, name='enable_course_registration'),
    path('instructor/disable-course-registration/', views.disable_course_registration, name='disable_course_registration'),
    # Instructor trash management
    path('instructor/trash/', views.instructor_trash_view, name='instructor_trash'),
    path('instructor/courses/<int:course_id>/restore/', views.instructor_restore_course_view, name='instructor_restore_course'),
    path('instructor/enrollments/<int:enrollment_id>/drop/', views.instructor_drop_enrollment_view, name='instructor_drop_enrollment'),
    path('instructor/enrollments/<int:enrollment_id>/restore/', views.instructor_restore_enrollment_view, name='instructor_restore_enrollment'),
    path('instructor/courses/<int:course_id>/permanent-delete/', views.instructor_permanent_delete_course_view, name='instructor_permanent_delete_course'),
    path('instructor/enrollments/<int:enrollment_id>/permanent-delete/', views.instructor_permanent_delete_enrollment_view, name='instructor_permanent_delete_enrollment'),
    path('instructor/dropped-students/', views.instructor_get_dropped_students_view, name='instructor_get_dropped_students'),
    path('instructor/courses/restore-all/', views.instructor_restore_all_courses_view, name='instructor_restore_all_courses'),
    path('instructor/courses/restore-all-archived/', views.instructor_restore_all_archived_courses_view, name='instructor_restore_all_archived_courses'),
    path('instructor/courses/permanent-delete-all/', views.instructor_permanent_delete_all_courses_view, name='instructor_permanent_delete_all_courses'),
    path('instructor/attendance-reports/', views.instructor_attendance_reports_view, name='instructor_attendance_reports'),
    path('instructor/attendance-reports/download/', views.instructor_attendance_reports_download_view, name='instructor_attendance_reports_download'),
    path('instructor/attendance-record/update-status/', views.instructor_update_attendance_record_status_view, name='instructor_update_attendance_record_status'),
    path('enroll-course/', views.enroll_course_view, name='enroll_course'),
    path('verify-enrollment-code/', views.verify_enrollment_code_view, name='verify_enrollment_code'),
    path('unenroll-course/<int:enrollment_id>/', views.unenroll_course_view, name='unenroll_course'),
    # Student trash / dropped enrollments
    path('student/dropped-enrollments/', views.student_dropped_enrollments_view, name='student_dropped_enrollments'),
    path('student/enrollments/<int:enrollment_id>/restore/', views.student_restore_enrollment_view, name='student_restore_enrollment'),
    path('student/enrollments/<int:enrollment_id>/permanent-delete/', views.student_permanent_delete_enrollment_view, name='student_permanent_delete_enrollment'),
    path('', views.home_view, name='home'),
    # Admin dashboard routes
    path('admin-dashboard/', admin_views.admin_dashboard_view, name='admin_dashboard'),
    path('admin-dashboard/institutional-setup/', admin_views.admin_institutional_setup_view, name='admin_institutional_setup'),
    path('admin-dashboard/user-management/', admin_views.admin_user_management_view, name='admin_user_management'),
    path('admin-dashboard/departments/<int:department_id>/users/', admin_views.admin_department_users_view, name='admin_department_users'),
    path('admin-dashboard/courses/', admin_views.admin_courses_view, name='admin_courses'),
    path('admin-dashboard/departments/<int:department_id>/courses/', admin_views.admin_department_courses_view, name='admin_department_courses'),
    path('admin-dashboard/programs/<int:program_id>/courses/', admin_views.admin_program_courses_view, name='admin_program_courses'),
    path('admin-dashboard/courses/add/', admin_views.admin_add_course_view, name='admin_add_course'),
    path('admin-dashboard/courses/<int:course_id>/update/', admin_views.admin_update_course_view, name='admin_update_course'),
    path('admin-dashboard/courses/<int:course_id>/delete/', admin_views.admin_delete_course_view, name='admin_delete_course'),
    path('admin-dashboard/courses/<int:course_id>/', admin_views.admin_course_detail_view, name='admin_course_detail'),
    path('admin-dashboard/reports/', admin_views.admin_reports_view, name='admin_reports'),
    path('admin-dashboard/departments/add/', admin_views.admin_add_department_view, name='admin_add_department'),
    path('admin-dashboard/departments/add', admin_views.admin_add_department_view, name='admin_add_department_no_slash'),
    path('admin-dashboard/departments/<int:department_id>/update/', admin_views.admin_update_department_view, name='admin_update_department'),
    path('admin-dashboard/departments/<int:department_id>/delete/', admin_views.admin_delete_department_view, name='admin_delete_department'),
    path('admin-dashboard/programs/add/', admin_views.admin_add_program_view, name='admin_add_program'),
    path('admin-dashboard/programs/<int:program_id>/update/', admin_views.admin_update_program_view, name='admin_update_program'),
    path('admin-dashboard/programs/<int:program_id>/delete/', admin_views.admin_delete_program_view, name='admin_delete_program'),
    path('admin-dashboard/departments/<int:department_id>/programs/', admin_views.admin_department_programs_view, name='admin_department_programs'),
    path('admin-dashboard/programs/<int:program_id>/users/', admin_views.admin_program_users_view, name='admin_program_users'),
    path('admin-dashboard/notifications/', admin_views.admin_notifications_view, name='admin_notifications'),
    path('admin-dashboard/users/<int:user_id>/approve/', admin_views.admin_approve_user_view, name='admin_approve_user'),
    path('admin-dashboard/users/<int:user_id>/reject/', admin_views.admin_reject_user_view, name='admin_reject_user'),
    path('admin-dashboard/notifications/<int:notification_id>/read/', admin_views.admin_mark_notification_read_view, name='admin_mark_notification_read'),
    path('admin-dashboard/users/add-teacher/', admin_views.admin_add_teacher_view, name='admin_add_teacher'),
    path('admin-dashboard/users/add-student/', admin_views.admin_add_student_view, name='admin_add_student'),
    path('admin-dashboard/users/<int:user_id>/', admin_views.admin_user_detail_view, name='admin_user_detail'),
    path('admin-dashboard/users/<int:user_id>/delete/', admin_views.admin_delete_user_view, name='admin_delete_user'),
    path('admin-dashboard/programs/<int:program_id>/users/bulk-delete/', admin_views.admin_bulk_delete_users_view, name='admin_bulk_delete_users'),
    path('admin-dashboard/users/<int:user_id>/download-document/', admin_views.admin_download_user_document_view, name='admin_download_user_document'),
    path('admin-dashboard/users/download/', admin_views.admin_download_users_csv_view, name='admin_download_users_csv'),
    path('admin-dashboard/profile/update/', admin_views.admin_update_profile_view, name='admin_update_profile'),
    # Trash management
    path('admin-dashboard/trash/', admin_views.admin_trash_view, name='admin_trash'),
    path('admin-dashboard/departments/<int:department_id>/restore/', admin_views.admin_restore_department_view, name='admin_restore_department'),
    path('admin-dashboard/programs/<int:program_id>/restore/', admin_views.admin_restore_program_view, name='admin_restore_program'),
    path('admin-dashboard/users/<int:user_id>/restore/', admin_views.admin_restore_user_view, name='admin_restore_user'),
    path('admin-dashboard/departments/<int:department_id>/permanent-delete/', admin_views.admin_permanent_delete_department_view, name='admin_permanent_delete_department'),
    path('admin-dashboard/programs/<int:program_id>/permanent-delete/', admin_views.admin_permanent_delete_program_view, name='admin_permanent_delete_program'),
    path('admin-dashboard/users/<int:user_id>/permanent-delete/', admin_views.admin_permanent_delete_user_view, name='admin_permanent_delete_user'),
    path('admin-dashboard/trash/restore-all/', admin_views.admin_restore_all_trash_view, name='admin_restore_all_trash'),
    path('admin-dashboard/trash/delete-all/', admin_views.admin_delete_all_trash_view, name='admin_delete_all_trash'),
    # API endpoints for move students
    path('api/get-course-enrollments/', views.get_course_enrollments_view, name='api_get_course_enrollments'),
    path('api/get-course-sections/', views.get_course_sections_view, name='api_get_course_sections'),
    path('api/move-students-to-section/', views.move_students_to_section_view, name='api_move_students_to_section'),
    
    path('api/health-check/', views.api_health_check, name='api_health_check'),
    
    # ESP32 Fingerprint Sensor Communication
    path('api/esp32/config/', views.api_esp32_config, name='api_esp32_config'),
    path('api/esp32/scan-feedback/', views.api_esp32_scan_feedback, name='api_esp32_scan_feedback'),
    path('api/esp32/enrollment-complete/', views.api_esp32_enrollment_complete, name='api_esp32_enrollment_complete'),
    
    # WebSocket broadcast API endpoints
    path('api/broadcast-scan-update/', views.api_broadcast_scan_update, name='api_broadcast_scan_update'),
    path('api/broadcast-enrollment/', views.api_broadcast_enrollment, name='api_broadcast_enrollment'),  # For confirmation messages
    path('api/broadcast-enrollment-complete/', views.api_broadcast_enrollment_complete, name='api_broadcast_enrollment_complete'),
    path('api/scan-acknowledged/', views.api_scan_acknowledged, name='api_scan_acknowledged'),
    path('api/check-scan-acknowledged/', views.api_check_scan_acknowledged, name='api_check_scan_acknowledged'),
    
    # Frontend enrollment management
    path('api/start-enrollment/', views.api_start_enrollment, name='api_start_enrollment'),
    path('api/student/enroll/start/', views.api_start_enrollment, name='api_student_enroll_start'),  # Alias for compatibility
    path('api/student/enroll/status/', views.api_student_enrollment_status, name='api_student_enroll_status'),
    path('api/student/enroll/cancel/', views.api_student_enroll_cancel, name='api_student_enroll_cancel'),
    path('api/enrollment-status/<str:enrollment_id>/', views.api_enrollment_status, name='api_enrollment_status'),
    path('api/enrollment-updates/<str:enrollment_id>/', views.api_enrollment_updates, name='api_enrollment_updates'),
    path('api/save-enrollment/', views.api_save_enrollment, name='api_save_enrollment'),
    path('api/biometric/confirm-enrollment/', views.api_biometric_confirm_enrollment, name='api_biometric_confirm_enrollment'),
    path('api/biometric/cancel-enrollment/', views.api_biometric_cancel_enrollment, name='api_biometric_cancel_enrollment'),
    path('api/get-enrolled-courses-status/', views.get_enrolled_courses_status_view, name='get_enrolled_courses_status'),
    # Instructor Biometric Scanning (Combined QR + Biometric Attendance)
    path('instructor/biometric-pending/', views.instructor_get_biometric_pending_view, name='instructor_get_biometric_pending'),
    path('api/instructor/attendance/start/', views.instructor_start_biometric_detection_view, name='instructor_start_biometric_detection'),
    path('api/instructor/attendance/stop/', views.instructor_stop_biometric_detection_view, name='instructor_stop_biometric_detection'),
    path('instructor/biometric-scan-attendance/', views.instructor_biometric_scan_attendance_view, name='instructor_biometric_scan_attendance'),
    path('get-course-attendance-count/', views.get_course_attendance_count, name='get_course_attendance_count'),
    # Student Biometric Registration (separate from attendance)
    path('student/fingerprint-pending/', views.student_fingerprint_pending_view, name='student_fingerprint_pending'),
    # ESP32 Fingerprint Detection (sent directly from sensor)
    # Supports mode parameter: 'registration' (students) or 'attendance' (instructors)
    path('api/fingerprint-detection/', views.fingerprint_detection_view, name='fingerprint_detection'),
]
