# Generated by Django 5.2.7 on 2025-11-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Program code (e.g., BSCpE, BSEE)', max_length=20)),
                ('name', models.CharField(help_text='Full program name (e.g., Bachelor of Science in Computer Engineering)', max_length=200)),
                ('school_name', models.CharField(blank=True, help_text='School name - programs are separated by school', max_length=200, null=True)),
                ('education_level', models.CharField(choices=[('high_senior', 'High/Senior High'), ('university_college', 'University/College')], default='university_college', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
