# Generated by Django 5.0.2 on 2025-11-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.CharField(default='', help_text='Parent Department / College (e.g., College of Engineering)', max_length=200),
        ),
    ]
