# Generated by Django 5.0.2 on 2025-11-07 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_adminnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code (e.g., CS 101, MATH 203)', max_length=50)),
                ('name', models.CharField(help_text='Course name (e.g., Introduction to Computer Science)', max_length=200)),
                ('year_level', models.IntegerField(help_text='Year level this course is for (1, 2, 3, 4, etc.)')),
                ('section', models.CharField(help_text='Section (e.g., A, B, 1, 2)', max_length=50)),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('summer', 'Summer')], default='1st', help_text='Semester', max_length=20)),
                ('school_year', models.CharField(blank=True, help_text='School year (e.g., 2024-2025)', max_length=20, null=True)),
                ('room', models.CharField(blank=True, help_text='Room/Location (e.g., Bldg A, Rm 302, Online/Zoom)', max_length=100, null=True)),
                ('days', models.CharField(help_text='Days of the week (e.g., Mon,Wed,Fri or Tue,Thu)', max_length=50)),
                ('start_time', models.TimeField(help_text='Class start time')),
                ('end_time', models.TimeField(help_text='Class end time')),
                ('attendance_start', models.TimeField(blank=True, help_text='Attendance check-in start time', null=True)),
                ('attendance_end', models.TimeField(blank=True, help_text='Attendance check-in end time', null=True)),
                ('enrollment_code', models.CharField(blank=True, help_text='Enrollment code for students', max_length=20, null=True)),
                ('school_name', models.CharField(blank=True, help_text='School name', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, help_text='Instructor/Teacher', limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(help_text='Program this course belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='dashboard.program')),
            ],
            options={
                'ordering': ['program', 'year_level', 'code'],
                'unique_together': {('program', 'year_level', 'section', 'code', 'semester', 'school_year')},
            },
        ),
    ]
