# Generated by Django 5.0.2 on 2025-11-07 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemporaryPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text='Temporary password (stored in plain text for document generation)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_used', models.BooleanField(default=False, help_text='Set to True when user changes their password')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_password_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Temporary Password',
                'verbose_name_plural': 'User Temporary Passwords',
                'ordering': ['-created_at'],
            },
        ),
    ]
