# Generated by Django 5.2.7 on 2025-11-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_usertemporarypassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_code',
        ),
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default='#3C4770', help_text='Color code for timetable display (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='course',
            name='attendance_end',
            field=models.TimeField(blank=True, help_text='Attendance check-in end time (set by instructor)', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='attendance_start',
            field=models.TimeField(blank=True, help_text='Attendance check-in start time (set by instructor)', null=True),
        ),
    ]
