# Generated by Django 5.2.7 on 2025-11-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_course_enrollment_code_course_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department/College name (e.g., College of Engineering)', max_length=200)),
                ('school_name', models.CharField(blank=True, help_text='School name - departments are separated by school', max_length=200, null=True)),
                ('education_level', models.CharField(choices=[('high_senior', 'High/Senior High'), ('university_college', 'University/College')], default='university_college', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'school_name')},
            },
        ),
    ]
