# Generated by Django 5.0.2 on 2025-11-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'school_name')},
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text='Department code (e.g., COE, CAS, CBME)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icon/picture for department folder', null=True, upload_to='department_icons/'),
        ),
        migrations.AddField(
            model_name='program',
            name='department_code',
            field=models.CharField(blank=True, help_text='Department code for quick reference', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icon/picture for program folder', null=True, upload_to='program_icons/'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('code', 'school_name'), ('name', 'school_name')},
        ),
    ]
