# Generated by Django 5.0.2 on 2025-11-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_department_unique_together_department_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('code', 'school_name'), name='unique_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name', 'school_name'), name='unique_name_per_school'),
        ),
    ]
