# Generated by Django 5.0.2 on 2025-11-11 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_course_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('start_time', models.TimeField(help_text='Class start time for this day')),
                ('end_time', models.TimeField(help_text='Class end time for this day')),
                ('room', models.CharField(blank=True, help_text='Room/Location for this day (optional, overrides course room)', max_length=100, null=True)),
                ('day_order', models.IntegerField(default=0, help_text='Order for sorting days')),
                ('course', models.ForeignKey(help_text='Course this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='dashboard.course')),
            ],
            options={
                'verbose_name': 'Course Schedule',
                'verbose_name_plural': 'Course Schedules',
                'ordering': ['day_order', 'start_time'],
                'unique_together': {('course', 'day')},
            },
        ),
    ]
