# Generated by Django 5.2.7 on 2025-11-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_add_course_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp - item will be permanently deleted after 30 days', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp - item will be permanently deleted after 30 days', null=True),
        ),
    ]
