# Generated by Django 5.0.2 on 2025-11-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_department_deleted_at_program_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='attendance_end',
            field=models.TimeField(blank=True, help_text='Attendance check-in end time for this day (optional, overrides course attendance_end)', null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='attendance_start',
            field=models.TimeField(blank=True, help_text='Attendance check-in start time for this day (optional, overrides course attendance_start)', null=True),
        ),
    ]
