# Generated by Django 5.0.2 on 2025-11-14 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(blank=True, help_text='Unique enrollment code for students to enroll in this course', max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Student's full name", max_length=90)),
                ('year_level', models.IntegerField(help_text="Student's year level")),
                ('section', models.CharField(help_text="Student's section", max_length=50)),
                ('email', models.EmailField(help_text="Student's school email", max_length=254)),
                ('student_id_number', models.CharField(help_text="Student's ID number", max_length=50)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, help_text='When the student enrolled')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the enrollment is active')),
                ('course', models.ForeignKey(help_text='Course the student is enrolling in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='dashboard.course')),
                ('student', models.ForeignKey(help_text='Student enrolling in the course', limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('course', 'student')},
            },
        ),
    ]
