# Generated by Django 5.0.2 on 2025-11-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_course_enrollment_code_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='category',
            field=models.CharField(choices=[('system', 'System'), ('enrollment', 'Enrollment'), ('course', 'Course'), ('account', 'Account'), ('general', 'General')], default='general', help_text='Category for organizing notifications', max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('course_assigned', 'Course Assigned'), ('course_updated', 'Course Updated'), ('attendance_reminder', 'Attendance Reminder'), ('system_alert', 'System Alert'), ('account_approved', 'Account Approved'), ('account_rejected', 'Account Rejected'), ('welcome', 'Welcome Message'), ('student_enrolled', 'Student Enrolled'), ('general', 'General Notification')], default='general', max_length=50),
        ),
    ]
