# Generated by Django 5.0.2 on 2025-11-15 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_usernotification_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section identifier (e.g., BSIT-A, Section 1)', max_length=50)),
                ('days', models.CharField(blank=True, help_text='Comma-separated days if using synchronized schedule', max_length=50)),
                ('start_time', models.TimeField(blank=True, help_text='Start time for synchronized schedule', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time for synchronized schedule', null=True)),
                ('room', models.CharField(blank=True, help_text='Room/Location for this section', max_length=100, null=True)),
                ('attendance_start', models.TimeField(blank=True, help_text='Attendance start for this section', null=True)),
                ('attendance_end', models.TimeField(blank=True, help_text='Attendance end for this section', null=True)),
                ('color', models.CharField(blank=True, help_text='Optional override color for this section', max_length=7, null=True)),
                ('has_day_schedules', models.BooleanField(default=False, help_text='True if this section uses day-specific schedules')),
                ('day_schedules', models.JSONField(blank=True, help_text='Stored day-specific schedules for this section', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_variants', to='dashboard.course')),
            ],
            options={
                'verbose_name': 'Course Section',
                'verbose_name_plural': 'Course Sections',
                'ordering': ['course', 'name'],
                'unique_together': {('course', 'name')},
            },
        ),
    ]
