# Generated by Django 5.0.2 on 2025-11-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_coursesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp - item will be permanently deleted after 30 days', null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp - item will be permanently deleted after 30 days', null=True),
        ),
        migrations.DeleteModel(
            name='CourseSection',
        ),
    ]
