# Generated by Django 5.0.2 on 2025-11-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_course_deleted_at_courseenrollment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive flag - for storing completed sessions'),
        ),
    ]
