# Generated by Django 5.0.2 on 2025-11-21 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_course_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendance_status',
            field=models.CharField(choices=[('closed', 'Closed Attendance'), ('open', 'Open Attendance'), ('stopped', 'Stop Attendance')], default='closed', help_text='Current attendance status for the course', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='qr_code',
            field=models.CharField(blank=True, help_text='Unique QR code for this course section', max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(help_text='Date of attendance')),
                ('attendance_time', models.TimeField(help_text='Time when attendance was recorded')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='present', help_text='Attendance status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course for this attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.course')),
                ('enrollment', models.ForeignKey(help_text='Enrollment record', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.courseenrollment')),
                ('student', models.ForeignKey(help_text='Student who attended', limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-attendance_date', '-attendance_time'],
                'unique_together': {('course', 'student', 'attendance_date')},
            },
        ),
    ]
