# Generated by Django 5.0.2 on 2025-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_course_attendance_status_course_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attendance_status',
            field=models.CharField(choices=[('automatic', 'Automatic (Based on Attendance Window)'), ('closed', 'Closed Attendance'), ('open', 'Open Attendance'), ('stopped', 'Stop Attendance')], default='automatic', help_text='Current attendance status for the course', max_length=20),
        ),
    ]
