# Generated by Django 5.0.2 on 2025-11-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_course_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_status',
            field=models.CharField(choices=[('open', 'Open for Enrollment'), ('closed', 'Closed Enrollment')], default='open', help_text='Enrollment status - controls whether students can enroll using the enrollment code', max_length=20),
        ),
    ]
