# Generated by Django 5.0.2 on 2025-11-22 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_course_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text='Custom password (stored in plain text for display)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_password_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Custom Password',
                'verbose_name_plural': 'User Custom Passwords',
                'ordering': ['-updated_at'],
            },
        ),
    ]
