# Generated by Django 5.0.2 on 2025-11-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_usercustompassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('course_assigned', 'Course Assigned'), ('course_updated', 'Course Updated'), ('attendance_reminder', 'Attendance Reminder'), ('system_alert', 'System Alert'), ('account_approved', 'Account Approved'), ('account_rejected', 'Account Rejected'), ('welcome', 'Welcome Message'), ('student_enrolled', 'Student Enrolled'), ('upcoming_class', 'Upcoming Class'), ('attendance_marked', 'Attendance Marked'), ('attendance_control_updated', 'Attendance Control Updated'), ('student_dropped', 'Student Dropped'), ('course_added', 'Course Added'), ('general', 'General Notification')], default='general', max_length=50),
        ),
    ]
