# Generated by Django 5.0.2 on 2025-11-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_add_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_teacher_signup', 'New Teacher Signup'), ('new_student_signup', 'New Student Signup'), ('teacher_approval_request', 'Teacher Approval Request'), ('system_alert', 'System Alert'), ('course_added', 'Course Added')], max_length=50),
        ),
    ]
