# Generated by Django 5.0.2 on 2025-11-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_add_admin_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='qr_code',
            field=models.CharField(blank=True, help_text='Unique QR code for this specific day schedule', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='qr_code_date',
            field=models.DateField(blank=True, help_text='Date when QR code was generated for this day', null=True),
        ),
    ]
