# Generated by Django 5.2.7 on 2025-11-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_courseschedule_qr_code_courseschedule_qr_code_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic (Based on Attendance Window)'), ('closed', 'Closed Attendance'), ('open', 'Open Attendance'), ('stopped', 'Stop Attendance'), ('postponed', 'Postponed')], default='automatic', help_text='Attendance status for this specific day schedule (overrides course-level status if set)', max_length=20, null=True),
        ),
    ]
