# Generated by Django 5.2.7 on 2025-11-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_attendancerecord_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendance_present_duration',
            field=models.IntegerField(blank=True, help_text="Number of minutes counted as 'present' from session open (instructor-set)", null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='qr_code_opened_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the QR/session was opened by the instructor', null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='attendance_present_duration',
            field=models.IntegerField(blank=True, help_text="Number of minutes counted as 'present' from session open for this day (overrides course-level)", null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='qr_code_opened_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the QR/session was opened for this schedule', null=True),
        ),
    ]
