# Generated by Django 5.2.7 on 2025-11-26 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_course_attendance_present_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='enrollment',
            field=models.ForeignKey(blank=True, help_text='Enrollment record (preserved when enrollment is dropped)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='dashboard.courseenrollment'),
        ),
    ]
