# Generated by Django 5.2.7 on 2025-11-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_attendancerecord_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_time',
            field=models.TimeField(blank=True, help_text='Time when attendance was recorded (null for absent records)', null=True),
        ),
    ]
