# Generated by Django 5.2.7 on 2025-11-27 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_attendancerecord_attendance_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(help_text='QR code value/ID (can be school ID, UUID, or custom value)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this QR code registration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this QR code is registered for', on_delete=django.db.models.deletion.CASCADE, related_name='qr_registrations', to='dashboard.course')),
                ('registered_by', models.ForeignKey(help_text='Instructor who registered this QR code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_registrations_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student who owns this QR code', on_delete=django.db.models.deletion.CASCADE, related_name='qr_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Code Registration',
                'verbose_name_plural': 'QR Code Registrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['qr_code'], name='dashboard_q_qr_code_8b69e0_idx'), models.Index(fields=['course', 'is_active'], name='dashboard_q_course__e45735_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
