# Generated by Django 6.0 on 2025-12-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_qr_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='course_code',
            field=models.CharField(blank=True, help_text='Course code (e.g., CpE - 123)', max_length=50),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course_name',
            field=models.CharField(blank=True, help_text='Course name/subject (e.g., Fundamental of Mixed Signals and Sensors)', max_length=200),
        ),
    ]
