# Generated by Django 6.0 on 2025-12-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_add_course_info_to_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='course_section',
            field=models.CharField(blank=True, help_text='Course section (e.g., A, B, 1, 2 - which section of the course the student is in)', max_length=50),
        ),
    ]
