# Generated by Django 6.0 on 2025-12-12 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_add_course_section_to_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qrcoderegistration',
            name='uq_active_qr_code',
        ),
        migrations.AddConstraint(
            model_name='qrcoderegistration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('qr_code', 'course'), name='uq_active_qr_code_per_course'),
        ),
    ]
