# Generated by Django 5.0.2 on 2025-12-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_remove_qrcoderegistration_uq_active_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustompassword',
            name='old_password',
            field=models.CharField(blank=True, help_text='Previous custom password (for tracking password history)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('postponed', 'Postponed')], default='present', help_text='Attendance status', max_length=20),
        ),
    ]
