# Generated by Django 5.0.2 on 2025-12-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_usercustompassword_old_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program this course belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='dashboard.program'),
        ),
    ]
