# Generated by Django 5.0.2 on 2025-12-19 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_instructorregistrationstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_data', models.TextField(help_text='Encrypted biometric data (fingerprint template)')),
                ('biometric_type', models.CharField(default='fingerprint', help_text='Type of biometric (e.g., fingerprint, face)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this biometric registration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this biometric is registered for', on_delete=django.db.models.deletion.CASCADE, related_name='biometric_registrations', to='dashboard.course')),
                ('student', models.ForeignKey(help_text='Student who owns this biometric data', on_delete=django.db.models.deletion.CASCADE, related_name='biometric_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Registration',
                'verbose_name_plural': 'Biometric Registrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'is_active'], name='dashboard_b_course__1c203c_idx'), models.Index(fields=['student', 'is_active'], name='dashboard_b_student_36f0d9_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
