# Generated by Django 5.0.2 on 2025-12-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_biometricregistration'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='qrcoderegistration',
            name='dashboard_q_qr_code_8b69e0_idx',
        ),
    ]
