# Generated by Django 5.0.2 on 2025-12-19 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_remove_global_qr_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrcoderegistration',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='qrcoderegistration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'course'), name='uq_student_per_course'),
        ),
    ]
