# Generated by Django 5.0.2 on 2025-12-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_fix_unique_constraint_for_cross_course_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricregistration',
            name='fingerprint_id',
            field=models.IntegerField(blank=True, help_text='Unique fingerprint ID assigned by the Arduino R307 sensor', null=True),
        ),
    ]
