# Generated by Django 6.0 on 2025-12-29 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_biometricregistration_dashboard_b_fingerp_316724_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='biometricregistration',
            name='unique_active_fingerprint_id',
        ),
        migrations.RemoveIndex(
            model_name='biometricregistration',
            name='dashboard_b_fingerp_316724_idx',
        ),
        migrations.AddIndex(
            model_name='biometricregistration',
            index=models.Index(fields=['fingerprint_id', 'course', 'is_active'], name='dashboard_b_fingerp_528684_idx'),
        ),
        migrations.AddConstraint(
            model_name='biometricregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'fingerprint_id'), name='unique_student_fingerprint_id'),
        ),
    ]
