# Generated by Django 6.0 on 2026-01-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_remove_biometricregistration_unique_active_fingerprint_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='biometricregistration',
            name='unique_student_fingerprint_id',
        ),
    ]
