# Generated by Django 5.0.2 on 2025-11-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_admin_customuser_school_name'),
        ('dashboard', '0003_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program/Major for university/college students and teachers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.program'),
        ),
    ]
