# Generated by Django 5.0.2 on 2025-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, help_text='Section (e.g., A, B, 1, 2)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_level',
            field=models.IntegerField(blank=True, help_text='Year level (1, 2, 3, 4, etc.)', null=True),
        ),
    ]
