# Generated by Django 5.0.2 on 2025-11-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_section_customuser_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, help_text='Department', max_length=200, null=True),
        ),
    ]
