# Generated by Django 5.2.7 on 2025-11-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp - item will be permanently deleted after 30 days', null=True),
        ),
    ]
