# Generated by Django 5.0.2 on 2025-11-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_password',
            field=models.CharField(blank=True, help_text="User's custom password (hashed)", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, help_text='OTP code for password reset', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='OTP expiration timestamp', null=True),
        ),
    ]
