# Generated by Django 5.0.2 on 2025-12-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_custom_password_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='program_text',
            field=models.CharField(blank=True, help_text='User-entered program/major text (for free-text entry)', max_length=300, null=True),
        ),
    ]
