# Generated by Django 5.0.2 on 2025-12-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_program_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name_text',
            field=models.CharField(blank=True, help_text='First name(s)', max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_text',
            field=models.CharField(blank=True, help_text='Last name(s)', max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name_text',
            field=models.CharField(blank=True, help_text='Middle name(s)', max_length=90, null=True),
        ),
    ]
