# Generated by Django 5.0.2 on 2025-12-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_first_name_text_customuser_last_name_text_and_more'),
    ]

    operations = [
    ]
