# Generated by Django 5.0.2 on 2025-12-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_populate_name_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name_text',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name_text',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='middle_name_text',
        ),
        migrations.AddField(
            model_name='customuser',
            name='qr_code_id',
            field=models.CharField(blank=True, help_text="Student's registered QR code ID (must be unique globally - only this student can use this QR code)", max_length=500, null=True, unique=True),
        ),
    ]
