# Generated by Django 6.0 on 2025-12-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_customuser_first_name_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='qr_code_id',
            field=models.CharField(blank=True, help_text="Student's registered QR code ID (must be unique globally - only this student can use this QR code). NOTE: unique=True removed to allow migrations. Use custom validation in views instead.", max_length=500, null=True),
        ),
    ]
